name: Spring Boot Project Build (Frostini)
on:
  push:
    branches: [main, dev]
  pull_request:
     branches: [main, dev]
jobs:
  build:
    name: Frostini Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build frostini Spring boot Application
        run: docker-compose build frostini # build frostini docker

      - name: Start frostini Spring boot Application
        run: export FROSTINI_ID=$(docker-compose run -p 8083:8083 -d frostini) ; docker network inspect tqs-delivery-p1g2_backend-frostini # start frostini docker

      - name: Build frostini pwa react app
        run: docker-compose build --build-arg API_HOSTNAME=localhost frostini-web # build frostini-web docker with the correct ip for the frostiniSpringBootDocker

      - name: Start frostini pwa react app
        run: docker-compose run -p 3000:80 -d frostini-web # run frostini-web and map port 80 to host's port 3000


      - name: Curl in localhost3000 to assert that seb service is running
        run: |
          sleep 5
          curl localhost:3000

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.TQS_FROSTINI }}
        run: mvn -B verify integration-test test org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sophjane_tqs-delivery-p1g2_frostini --file projFrostini/backend/frostini/pom.xml
